[2025-03-19T00:00:09.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T00:00:09.083+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sevdesk_contact_pipeline.create_or_update_contact scheduled__2025-03-18T23:00:00+00:00 [queued]>
[2025-03-19T00:00:09.206+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sevdesk_contact_pipeline.create_or_update_contact scheduled__2025-03-18T23:00:00+00:00 [queued]>
[2025-03-19T00:00:09.207+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-19T00:00:09.235+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_or_update_contact> on 2025-03-18 23:00:00+00:00
[2025-03-19T00:00:09.240+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2356) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-19T00:00:09.241+0000] {standard_task_runner.py:72} INFO - Started process 2361 to run task
[2025-03-19T00:00:09.242+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sevdesk_contact_pipeline', 'create_or_update_contact', 'scheduled__2025-03-18T23:00:00+00:00', '--job-id', '1054', '--raw', '--subdir', 'DAGS_FOLDER/sevdesk_contact_pipeline.py', '--cfg-path', '/tmp/tmpj625ydsf']
[2025-03-19T00:00:09.243+0000] {standard_task_runner.py:105} INFO - Job 1054: Subtask create_or_update_contact
[2025-03-19T00:00:09.280+0000] {task_command.py:467} INFO - Running <TaskInstance: sevdesk_contact_pipeline.create_or_update_contact scheduled__2025-03-18T23:00:00+00:00 [running]> on host e54e5582f32f
[2025-03-19T00:00:09.328+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sevdesk_contact_pipeline' AIRFLOW_CTX_TASK_ID='create_or_update_contact' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T23:00:00+00:00'
[2025-03-19T00:00:09.329+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-19T00:00:09.329+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-19T00:00:09.329+0000] {logging_mixin.py:190} INFO - Current task name:create_or_update_contact state:running start_date:2025-03-19 00:00:09.083722+00:00
[2025-03-19T00:00:09.329+0000] {logging_mixin.py:190} INFO - Dag name:sevdesk_contact_pipeline and current dag run status:running
[2025-03-19T00:00:09.330+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T00:00:09.479+0000] {logging_mixin.py:190} INFO - ‚ùå Failed to create contact: {"status":401,"message":"Authentication required"}
[2025-03-19T00:00:09.480+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T00:00:09.484+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T00:00:09.485+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=sevdesk_contact_pipeline, task_id=create_or_update_contact, run_id=scheduled__2025-03-18T23:00:00+00:00, execution_date=20250318T230000, start_date=20250319T000009, end_date=20250319T000009
[2025-03-19T00:00:09.506+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-19T00:00:09.506+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-19T00:00:09.506+0000] {logging_mixin.py:190} INFO - Dag name:sevdesk_contact_pipeline queued_at:2025-03-19 00:00:00.048676+00:00
[2025-03-19T00:00:09.507+0000] {logging_mixin.py:190} INFO - Task hostname:e54e5582f32f operator:PythonOperator
[2025-03-19T00:00:09.551+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T00:00:09.566+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-19T00:00:09.567+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
