[2025-03-17T21:45:02.551+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T21:45:02.560+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sevdesk_to_hubspot_sync_dynamic.process_and_create_contact scheduled__2025-03-17T21:40:00+00:00 [queued]>
[2025-03-17T21:45:02.650+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sevdesk_to_hubspot_sync_dynamic.process_and_create_contact scheduled__2025-03-17T21:40:00+00:00 [queued]>
[2025-03-17T21:45:02.651+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-17T21:45:02.656+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_and_create_contact> on 2025-03-17 21:40:00+00:00
[2025-03-17T21:45:02.659+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1669) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T21:45:02.660+0000] {standard_task_runner.py:72} INFO - Started process 1670 to run task
[2025-03-17T21:45:02.660+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sevdesk_to_hubspot_sync_dynamic', 'process_and_create_contact', 'scheduled__2025-03-17T21:40:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dynamicsensor_dag.py', '--cfg-path', '/tmp/tmpjtvawv6y']
[2025-03-17T21:45:02.661+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask process_and_create_contact
[2025-03-17T21:45:02.683+0000] {task_command.py:467} INFO - Running <TaskInstance: sevdesk_to_hubspot_sync_dynamic.process_and_create_contact scheduled__2025-03-17T21:40:00+00:00 [running]> on host 07f4f36f3e31
[2025-03-17T21:45:02.715+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sevdesk_to_hubspot_sync_dynamic' AIRFLOW_CTX_TASK_ID='process_and_create_contact' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T21:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T21:40:00+00:00'
[2025-03-17T21:45:02.716+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T21:45:02.716+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T21:45:02.716+0000] {logging_mixin.py:190} INFO - Current task name:process_and_create_contact state:running start_date:2025-03-17 21:45:02.561172+00:00
[2025-03-17T21:45:02.716+0000] {logging_mixin.py:190} INFO - Dag name:sevdesk_to_hubspot_sync_dynamic and current dag run status:running
[2025-03-17T21:45:02.717+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T21:45:02.720+0000] {logging_mixin.py:190} INFO - ‚ùå No new contact found to create in HubSpot.
[2025-03-17T21:45:02.721+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T21:45:02.725+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T21:45:02.726+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=sevdesk_to_hubspot_sync_dynamic, task_id=process_and_create_contact, run_id=scheduled__2025-03-17T21:40:00+00:00, execution_date=20250317T214000, start_date=20250317T214502, end_date=20250317T214502
[2025-03-17T21:45:02.734+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-17T21:45:02.734+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-17T21:45:02.735+0000] {logging_mixin.py:190} INFO - Dag name:sevdesk_to_hubspot_sync_dynamic queued_at:2025-03-17 21:45:00.893346+00:00
[2025-03-17T21:45:02.735+0000] {logging_mixin.py:190} INFO - Task hostname:07f4f36f3e31 operator:PythonOperator
[2025-03-17T21:45:02.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T21:45:02.764+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
